server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curestore?serverTimezone=GMT%2b8
    username: root
    password: 123456
  application:
    name: order-service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/aliano/mapper/xml/*.xml
#rocketmq:
#  name-server: 47.110.92.174:9876
#  producer:
#    group: order