server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/corestore?serverTimezone=GMT%2b8
    username: root
    password: 123456
  application:
    name: product-service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/aliano/mapper/xml/*.xml
